---
title: "Paneles"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    logo: logo.JPG
    favicon: logo.JPG
    theme: yeti
runtime: shiny  

---

```{r global, include=FALSE}
library(flexdashboard)
library(ggplot2)
library(plotly)
library(DT)
library(stringr)
library(tidyr)
library(highcharter)

source("funciones.R")

#entradas de fruta
entradas_fruta <- entradas.fruta(Campos = c("Fecha", "Clave_productor", "Clave_producto", "Aceptadas", "Clave_acopio"))

#entradas de material
entradas_material <- entradas.material()

entregas_material <- entregas.material(Campos = c( "Tipo_salida", "Clave_productor", 
                                      "Fecha", "Cantidad", "Clave_material",
                                      "Tipo_receptor", "Clave_acopio"))



#productores activos
productores <-   data.frame(Clave_productor = unique(entradas_fruta$Clave_productor))%>%
    nombres.productores()%>%
    rename(Codigo = Clave_productor)
#acopios
acopios <- data.frame(Clave_acopio = unique(entradas_fruta$Clave_acopio))%>%
  get.acopio()

#Pesos de las presentaciones
presentaciones <-  merge(myfetch("tbProductos")%>%
        filter(strCan_cel == "NO"),
      myfetch("tbPresentaciones")%>%
        filter(strCan_cel == "NO"), 
      by = "intCla_pre", suffixes = c("h", "b"))%>%
  transmute(Clams = as.integer(intCan_tid), Peso = as.numeric(intPes_o), 
            Unidad = strUni_med)%>%
   filter(Unidad == "OZ")%>%
  mutate(Presentacion = paste0(Clams,"X", Peso, Unidad))%>%
   unique()%>%
   mutate(Peso_total = Peso *Clams)%>%
   select(Presentacion, Peso_total)

#Lista de materiales  
load.materiales(Campos = c("Material"))


materiales <- setNames(materiales$Clave_material, materiales$Material)



entradas_totales <- ddply(entradas_fruta%>%
                            select(Fecha, Clave_producto, Aceptadas, Clave_acopio)%>%
                            tiempos("Semana"),
                          .(Semana, Clave_producto, Clave_acopio), summarize, Total = sum(Aceptadas))



```

PRODUCTORES
==========================================================================

Inputs {.sidebar}
-------------------------------------------------------------------

###
```{r}

selectizeInput("Acopio", label = "Selecione un Acopio",
            choices = setNames(acopios$Clave_acopio, acopios$Acopio),
            options = list(placeholder = 'Seleccione  un Acopio', maxItems = 1), 
            multiple = TRUE)


selectizeInput("Productor", label = "Productores",
            choices = paste(productores$Codigo,productores$Nombre_completo), 
            options = list(placeholder = 'Seleccione un productor', maxItems = 1), multiple = TRUE)


conditionalPanel(condition = "input.Acopio != null || input.Productor != null", 
              
                          selectInput("INTERVALO", "Ver por:",
                                      choices = c("Semana", "Diario"),
                                      selected = "Semana")
            
)


selectInput("Presentacion", "Produccion en:",
            choices = presentaciones$Presentacion,
            selected = "12X6OZ")



renderUI({
  
  frutas <- data.frame(Clave_producto = unique(entradas_prod_ini()$Clave_producto))%>%
    get.productos("Fruta")

  
  selectizeInput("Frutas", "Frutas", choices = unique(frutas$Fruta), multiple = TRUE, selected = unique(frutas$Fruta))
  
  
})

# Productos input

renderUI({

productos <-  data.frame(Clave_producto = unique(entradas_prod_ini()$Clave_producto))%>%
    get.productos("Producto")

selectizeInput("Producto", label = "Filtre un producto", options = list(placeholder = "Seleccione un producto"),
                          choices = productos$Producto, multiple = TRUE)

})


#Fechas input 

dateRangeInput("Fechas", "Seleccione un rango", start = inicio_temporada, end = max(entradas_fruta$Fecha))


peso <- reactive({merge(data.frame(Presentacion = input$Presentacion), presentaciones)})

#entradas inicial

entradas_prod_ini <- reactive({

  if(is.null(input$Acopio) & is.null(input$Productor)){
    
    entradas_totales%>%
      ddply(.(Semana, Clave_producto), summarize, Total = sum(Total))%>%
       get.productos(Campos = c("Fruta", "Nombre_producto", "Presentacion",  "Producto"))%>%
      merge(presentaciones)%>%
      mutate(Fraccion = Peso_total/peso()$Peso_total)
      
    
  }else{
    
    if(!is.null(input$Acopio) & is.null(input$Productor)){
     
    entradas_fruta%>%
    select(Fecha, Clave_producto, Aceptadas, Clave_acopio)%>%
        filter(Clave_acopio == input$Acopio)%>%
    ddply(.(Fecha, Clave_producto), summarize, Total = sum(Aceptadas))%>%
    get.productos(Campos = c("Fruta", "Nombre_producto", "Presentacion", "Producto"))%>%
          merge(presentaciones)%>%
      mutate(Fraccion = Peso_total/peso()$Peso_total)%>%
    filter(Fecha > input$Fechas[1], Fecha < input$Fechas[2])%>%
        tiempos("Semana")
       
      
    }else{
  
  
    
  entradas_fruta%>%
    select(Fecha, Clave_productor, Clave_producto, Aceptadas, Clave_acopio)%>%
        filter(Clave_productor %in% str_match(input$Productor, "^[[0-9]]{0,3}")[,1])%>%
    ddply(.(Fecha, Clave_productor, Clave_producto), summarize, Total = sum(Aceptadas))%>%
    get.productos(Campos = c("Fruta", "Nombre_producto", "Presentacion", "Producto"))%>%
          merge(presentaciones)%>%
      mutate(Fraccion = Peso_total/peso()$Peso_total)%>%
    filter(Fecha > input$Fechas[1], Fecha < input$Fechas[2])
    
  }}
    
})



entradas_productor <- reactive({  
  
  if(input$INTERVALO == "Diario"){  
x  <-  entradas_prod_ini()%>%
      filter(Fruta %in% input$Frutas)
      
    
  }else{
    
   
x <- entradas_prod_ini()%>%
         filter(Fruta %in% input$Frutas)
     
    }
  

if(!is.null(input$Producto)){
  
  x%>%
    filter(Producto %in% input$Producto)

  } else {
  
    x
}
  
})

presentacion <- reactive({
  input$Presentacion
})

```




Nombre
--------------------------------------------------------------------------

###Nombre
```{r}

stats <- reactive({
  
  
if(is.null(input$Acopio) & is.null(input$Productor)){
  
  entradas_productor()%>%
  ddply(.(Semana), summarize, Total = sum(Total*Fraccion))%>%
  filter(Total != 0)%>%
  summarize( Maximo = round(max(Total),2),
             Minimo = round(min(Total),2),
             Acumulado = round(sum(Total)))
  
}else{
  if(!is.null(input$Acopio) & is.null(input$Productor)){
  
    if(input$INTERVALO == "Diario"){
  
entradas_productor()%>%
  ddply(.(Fecha), summarize, Total = sum(Total*Fraccion))%>%
      filter(Total != 0)%>%
    summarize(Maximo = round(max(Total),2),
             Minimo = round(min(Total),2),
             Acumulado = round(sum(Total)))
  
  }else{
  
  if(input$INTERVALO == "Semana"){
    
entradas_productor()%>%
      tiempos("Semana")%>%
  ddply(.(Semana), summarize, Total = sum(Total*Fraccion))%>%
  filter(Total != 0)%>%
  summarize(Maximo = round(max(Total),2),
             Minimo = round(min(Total),2),
             Acumulado = round(sum(Total)))

    
  }
 
  }
  
  
}else{
  if(!is.null(input$Productor)){

  
  if(input$INTERVALO == "Diario"){
  
entradas_productor()%>%
  ddply(.(Fecha, Clave_productor), summarize, Total = sum(Total*Fraccion))%>%
      filter(Total != 0)%>%
  ddply(.(Clave_productor),
  summarize, Maximo = round(max(Total),2),
             Minimo = round(min(Total),2),
             Acumulado = round(sum(Total)))
  
  }else{
  
  if(input$INTERVALO == "Semana"){
    
entradas_productor()%>%
      tiempos("Semana")%>%
  ddply(.(Semana, Clave_productor), summarize, Total = sum(Total*Fraccion))%>%
  filter(Total != 0)%>%
      ddply(.(Clave_productor),
  summarize, Maximo = round(max(Total),2),
             Minimo = round(min(Total),2),
             Acumulado = round(sum(Total)))
    
  }
  }
}
}
}
})

renderValueBox(
if(is.null(input$Acopio) & is.null(input$Productor)){
valueBox("Produccion Total")
}else{
  if(!is.null(input$Acopio) & is.null(input$Productor)){
   valueBox(data.frame(Clave_acopio = input$Acopio)%>%
              get.acopio())
  }else{
    valueBox(input$Productor)
  }
}
)
```



Indicadores
-----------------------------------------------------------------------

### Maximo 

```{r }

renderValueBox(valueBox(stats()$Maximo))

```


###Minimo 
```{r }

renderValueBox(valueBox(stats()$Minimo))

```


### Ultima entrega
```{r}

renderValueBox(valueBox(max(entradas_productor()$Fecha)))

```

### Acumulado
```{r }

renderValueBox(valueBox(stats()$Acumulado))

```  



Visualizacion {.tabset}
-----------------------------------------------------------------------

### Produccion en 6oz
```{r}
renderHighchart(
 
if(is.null(input$Acopio) & is.null(input$Productor)){
        hchart(
      entradas_productor()%>%
        ddply(.(Semana), summarize, Total = sum(Total*Fraccion))%>%
        semanas(Campos = list(Total = 0)),
          hcaes(x = Semana, y = Total), type = "line")%>%
     hc_chart(zoomType = "xy", panKey = "ctrl", panning = TRUE)%>%
        hc_xAxis(categories = sort(unique(data.frame(Semana = factor(c(1:52), levels = (c(34:85)%%52 + 1), ordered = TRUE))[,1])))
 
}else{
  if(!is.null(input$Acopio) & is.null(input$Productor)){
    
    if(input$INTERVALO == "Semana"){
     
      hchart(
      entradas_productor()%>%
        ddply(.(Semana), summarize, Total = sum(Total*Fraccion))%>%
        semanas(Campos = list(Total = 0)),
          hcaes(x = Semana, y = Total), type = "line")%>%
     hc_chart(zoomType = "xy", panKey = "ctrl", panning = TRUE)%>%
        hc_xAxis(categories = sort(unique(data.frame(Semana = factor(c(1:52), levels = (c(34:85)%%52 + 1), ordered = TRUE))[,1])))
    }else{
      
      
      if(input$INTERVALO == "Diario"){
         
        hchart(
      entradas_productor()%>%
            ddply(.(Fecha), summarize, Total = sum(Total*Fraccion))%>%
            dias(Campos = list(Total = 0)), 
          hcaes(x = Fecha, y = Total), type = "line")%>%
    hc_chart(zoomType = "xy", panKey = "ctrl", panning = TRUE)
        
        
      }
    }
    
  }else{
       if(input$INTERVALO == "Semana"){
     
      hchart(
      entradas_productor()%>%
        tiempos("Semana")%>%
        ddply(.(Semana, Clave_productor), summarize, Total = sum(Total*Fraccion))%>%
        semanas(Campos = list(Total = 0, Clave_productor = str_match(input$Productor, "^[[0-9]]{0,3}")[,1])),
          hcaes(x = Semana, y = Total, group = Clave_productor), type = "line")%>%
     hc_chart(zoomType = "xy", panKey = "ctrl", panning = TRUE)%>%
        hc_xAxis(categories = sort(unique(data.frame(Semana = factor(c(1:52), levels = (c(34:85)%%52 + 1), ordered = TRUE))[,1])))
    }else{
      
      if(input$INTERVALO == "Diario"){
         
        hchart(
      entradas_productor()%>%
            ddply(.(Fecha, Clave_productor), summarize, Total = sum(Total*Fraccion))%>%
            dias(Campos = list(Total = 0, Clave_productor = str_match(input$Productor, "^[[0-9]]{0,3}")[,1])), 
          hcaes(x = Fecha, y = Total, group = Clave_productor), type = "line")%>%
    hc_chart(zoomType = "xy", panKey = "ctrl", panning = TRUE)
        
        
      }
    }
  }
} 
)
```


### Productos

```{r}

renderHighchart(
if(is.null(input$Acopio) & is.null(input$Productor)){
  myhcsemana(entradas_productor()%>%
          mutate(Producto = paste(Nombre_producto, Presentacion, Fruta))%>%
          ddply(.(Semana, Producto), summarize, Total = sum(Total)))
  
}else{
if(input$INTERVALO == "Diario"){
         
      hchart(entradas_productor()%>%
          mutate(Producto = paste(Nombre_producto, Presentacion, Fruta))%>%
          ddply(.(Fecha, Producto), summarize, Total = sum(Total)),
          hcaes(x = Fecha, y = Total, group = Producto), type = "column")%>%
    hc_chart(zoomType = "xy", panKey = "ctrl", panning = TRUE)
        
        
      }else{
     
      myhcsemana(entradas_productor()%>%
                   tiempos("Semana")%>%
          mutate(Producto = paste(Nombre_producto, Presentacion, Fruta))%>%
          ddply(.(Semana, Producto), summarize, Total = sum(Total)))
        
      }
}
)



```

### Tabla de Datos
```{r}

renderDataTable(
  
if(is.null(input$Acopio) & is.null(input$Productor)){  
  datatable(entradas_productor()%>%
              mutate(Total_presentacion = Total*Fraccion)%>%
              select(Nombre_producto, Presentacion, Fruta, Total, Total_presentacion, Semana)%>%
              arrange(Semana)
              )
}else{
  if(input$INTERVALO == "Semana"){
      datatable(entradas_productor()%>%
                  tiempos("Semana")%>%
              mutate(Total_presentacion = Total*Fraccion)%>%
              select(Nombre_producto, Presentacion, Fruta, Total, Total_presentacion, Semana)%>%
                ddply(.(Semana, Nombre_producto, Presentacion, Fruta),summarize,  Total = sum(Total), Total_presentacion = sum(Total_presentacion))%>%
              arrange(Semana))
              
  }else{
    if(input$INTERVALO == "Diario"){
           datatable(entradas_productor()%>%
              mutate(Total_presentacion = Total*Fraccion)%>%
                tiempos("Semana")%>%
              select(Fecha, Nombre_producto, Presentacion, Fruta, Total, Total_presentacion, Semana)%>%
              arrange(Fecha)
           )
      
    }
  }
}
)

```














MATERIALES
===========================================================================

inputs {.sidebar}
----------------------------------------------------------------------------

###
```{r}

selectizeInput("Acopio_m", label = "Selecione un Acopio",
            choices = setNames(acopios$Clave_acopio, acopios$Acopio),
            options = list(placeholder = 'Seleccione  un Acopio', maxItems = 1), 
            multiple = TRUE)


selectizeInput("Productor_m", label = "Productores",
            choices = paste(productores$Codigo,productores$Nombre_completo), 
            options = list(placeholder = 'Seleccione un productor', maxItems = 1), multiple = TRUE)


              
                          selectInput("INTERVALO", "Ver por:",
                                      choices = c("Semana", "Diario"),
                                      selected = "Semana")
            

conditionalPanel(condition = "input.Productor_m == null",                          

                 renderUI(
  selectizeInput("Material", label = "Selecione un material", options = list(placeholder = NULL),
                          choices = materiales, multiple = TRUE)
))

conditionalPanel(condition = "input.Productor_m != null", 
selectInput("Presentacion",  "Selecione un material",
            choices = presentaciones$Presentacion,
            selected = "12X6OZ")
)


flujos_acopio <- reactive({
 
  x <-  rbind(
  entradas_material%>%
    select(Fecha, Clave_acopio, Clave_material, Cantidad)%>%
    filter(Clave_acopio == input$Acopio_m),
  entregas_material%>%
    select(Fecha, Clave_acopio, Clave_material, Cantidad)%>%
    filter(Clave_acopio == input$Acopio_m)%>%
    mutate(Cantidad = -Cantidad))
 
 if(!is.null(input$Acopio_m)){
   if(!is.null(input$Material)){
     x%>%
       filter(Clave_acopio == input$Acopio_m, Clave_material == input$Material)
   }else{
     x%>%
       filter(Clave_acopio == input$Acopio_m)
   }
 }else{
   if(is.null(input$Acopio_m) & is.null(input$Productor_m)){
   x
     }
   }
 

})
  
flujos_productor <-  reactive({

  x  <-   entradas_fruta%>%
      filter(Clave_productor == str_match(input$Productor_m, "^[[0-9]]{0,3}")[,1])%>%
    ddply(.(Fecha, Clave_producto), summarize, Total = sum(Aceptadas))

  rbind(
                    #Cajas con fruta
      x%>%
        get.productos(Campos = c("Presentacion"))%>%
      select(Fecha, Presentacion,Total)%>%
      filter(Fecha >= inicio_temporada)%>%
      mutate(Tipo_material = "CAJA EMP.", Tipo = "FRUTA", Total = - Total),   #Cajas con fruta
                
                             #clams con fruta
    
      x%>%
        get.productos(Campos = c("Presentacion", "Peso", "Unidad", "Clams"))%>%
                  mutate(Total = Total*Clams,
                         Presentacion = paste0(Peso,Unidad))%>%
      select(Fecha, Presentacion, Total)%>%
      mutate(Tipo_material = "CLAMSHELL", Tipo = "FRUTA", Total = -Total),    
                
                #prestamos
      entregas_material%>%
      filter(Clave_productor == str_match(input$Productor_m, "^[[0-9]]{0,3}")[,1])%>%
                  filter(Tipo_salida == "PRESTAMO", Tipo_receptor == "PRODUCTOR")%>%
      select(Fecha, Clave_material, Cantidad)%>%
      rename(Total = Cantidad)%>%
      get.material(Campos = c("Presentacion", "Tipo_material")) %>%
      mutate(Tipo = "PRESTAMO")%>%
      select(Fecha, Presentacion, Total, Tipo_material, Tipo),
    
                #devoluciones
          
    entradas_material%>%
      rename(Clave_productor = Clave_proveedor)%>%
      filter(Clave_productor == str_match(input$Productor_m, "^[[0-9]]{0,3}")[,1])%>%
      filter(Tipo_entrada == "DEVOLUCION", Tipo_proveedor == "PRODUCTOR")%>%
      rename(Tipo = Tipo_entrada)%>%
      get.material(Campos = c("Presentacion", "Tipo_material"))%>%
      mutate(Total = -Cantidad)%>%
      select(Fecha, Presentacion, Total, Tipo_material, Tipo))%>%
    
              #summarize
    rename(Concepto = Tipo)%>%
    ddply(.(Fecha, Concepto,Tipo_material, Presentacion), summarize, 
          Total = sum(Total))%>%
    tiempos(Campos = c("Semana"))

})

```

Nombre
--------------------------------------------------------------------------

###Nombre
```{r}

renderValueBox(
  if(!is.null(input$Productor_m)){
    valueBox(input$Productor_m)
  }else{
  if(is.null(input$Productor_m)){
    valueBox(data.frame(Clave_acopio = input$Acopio_m)%>%
               get.acopio())
  }
}

)

```



Visualizaciones {.tabset}
-----------------------------------------------------------------------

###Grafico
```{r}
renderHighchart(
    if(!is.null(input$Productor_m)){
        hchart(flujos_productor()%>%
                 mutate(Total = ifelse(Tipo_material == "CLAMSHELL", Total/12, Total))%>%
             ddply(.(Fecha, Presentacion), summarize, Saldo = sum(Total)), hcaes(x = Fecha, y = Saldo, group = Presentacion), type = "line")%>%
           hc_chart(zoomType = "xy", panKey = "ctrl", panning = TRUE)
 
      }else{
  if(is.null(input$Productor_m) & !is.null(input$Acopio_m)){
    hchart(flujos_acopio()%>%
             mutate(Total = ifelse(Tipo_material == "CLAMSHELL", Total/12, Total))%>%
             ddply(.(Fecha, Clave_material), summarize, Saldo = sum(Cantidad))%>%
             get.material("Material") , hcaes(x = Fecha, y = Saldo, group = Material), type = "line")%>%
         hc_chart(zoomType = "xy", panKey = "ctrl", panning = TRUE)
  }
}
  

)
```


###Saldos

###Datos
```{r}
renderDataTable(datatable(flujos_productor()))
```



