---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
```

ACOPIOS{data-navmenu="PRODUCCION"}
==========================================================================

Acopio
--------------------------------------------------------------------------


###Nombre
```{r}

stats2 <- reactive({
  
  if(input$INTERVALO == "Diario"){
  
entradas_acopio()%>%
  ddply(.(Fecha, Clave_acopio), summarize, Total = sum(Total*Fraccion))%>%
      filter(Total != 0)%>%
  ddply(.(Clave_acopio),
  summarize, Maximo = round(max(Total),2),
             Minimo = round(min(Total),2),
             Acumulado = round(sum(Total)))
  
  }else{
  
  if(input$INTERVALO == "Semana"){
    
entradas_acopio()%>%
  ddply(.(Semana, Clave_acopio), summarize, Total = sum(Total*Fraccion))%>%
  filter(Total != 0)%>%
      ddply(.(Clave_acopio),
  summarize, Maximo = round(max(Total),2),
             Minimo = round(min(Total),2),
             Acumulado = round(sum(Total)))

    
  }
 
  } 
})

renderValueBox(valueBox(input$Acopio))

```


Cajas 
-----------------------------------------------------------------------


###Maximo en 6Oz

```{r }

renderValueBox(valueBox(stats2()$Maximo))

```


###Minimo en 6oz
```{r }

renderValueBox(valueBox(stats2()$Minimo))

```


### Ultima entrega
```{r}

renderValueBox(valueBox(max(entradas_acopio()$Fecha)))

```

### Acumulado en 6oz
```{r }

renderValueBox(valueBox(stats2()$Acumulado))

```  


Vusualizacion {.tabset}
-----------------------------------------------------------------------

### Produccion en 6oz
```{r}
renderHighchart(
 
    
    if(input$INTERVALO == "Semana"){
     
      hchart(
      entradas_acopio()%>%
        ddply(.(Semana, Clave_acopio), summarize, Total = sum(Total*Fraccion))%>%
           semanas(Campos = list(Total = 0, 
                                    Clave_acopio = input$Acopio)), 
          hcaes(x = Semana, y = Total, group = Clave_acopio), type = "line")%>%
     hc_chart(zoomType = "xy", panKey = "ctrl", panning = TRUE)
    }else{
      
      if(input$INTERVALO == "Diario"){
         
        hchart(
      entradas_acopio()%>%
            ddply(.(Fecha, Clave_acopio), summarize, Total = sum(Total*Fraccion))%>%
            dias(Campos = list(Total = 0, Clave_acopio = input$Acopio)), 
          hcaes(x = Fecha, y = Total, group = Clave_acopio), type = "line")%>%
    hc_chart(zoomType = "xy", panKey = "ctrl", panning = TRUE)
        
        
      }
    }
    
)
```


### Productos

```{r}

renderHighchart(
 
    
    if(input$INTERVALO == "Semana"){
     
      hchart(entradas_acopio()%>%
          mutate(Producto = paste(Nombre_producto, Presentacion, Fruta))%>%
          ddply(.(Semana, Producto), summarize, Total = sum(Total))%>%
            semanas(Campos = list(Total = 0, 
                                  Clave_acopio = input$Acopio,
                                  Producto = "ALPASA 12X6OZ ZAR CN")),
          hcaes(x = Semana, y = Total, group = Producto), type = "column")%>%
   hc_chart(zoomType = "xy", panKey = "ctrl", panning = TRUE)%>%
        hc_xAxis(categories = sort(unique(data.frame(Semana = factor(c(1:52), levels = (c(34:85)%%52 + 1), ordered = TRUE))[,1])))
    
        
    }else{
      
      if(input$INTERVALO == "Diario"){
         
      hchart(entradas_acopio()%>%
          mutate(Producto = paste(Nombre_producto, Presentacion, Fruta))%>%
          ddply(.(Fecha, Producto), summarize, Total = sum(Total)),
          hcaes(x = Fecha, y = Total, group = Producto), type = "column")%>%
    hc_chart(zoomType = "xy", panKey = "ctrl", panning = TRUE)
        
        
      }
    }
    
)



```

### Tabla de Datos
```{r}

renderDataTable(
  datatable(entradas_acopio()%>%
              mutate(Total_6oz = Total*Fraccion6oz)%>%
              select(Fecha, Nombre_producto, Presentacion, Fruta, Total, Total_6oz)
              )
)
```



PRODUCTORES  {data-navmenu="MATERIALES"}
=========================================================================================


Nombre
---------------------------------------------------------------------------------------------------------------

###Nombre
```{r}

renderValueBox(valueBox(input$Productor2))



```






Visualizacion {.tabset}
---------------------------------------------------------------------------------
###Saldos
```{r}






renderTable(
  flujos_productor()%>%
    select(-Semana)%>%
    rbind(data.frame(Fecha = inicio_temporada, Clave_productor = input$Productor2, 
                     Concepto = c("FRUTA", "DEVOLUCION", "PRESTAMO"), Tipo_material = "AUX", 
                     Presentacion = "6OZ", Total = 0))%>%
    ddply(.(Presentacion, Tipo_material, Concepto), summarize, Saldo = sum(Total))%>%
    spread(Concepto, Saldo, fill = 0 )%>%
    select(Tipo_material, Presentacion,  PRESTAMO, FRUTA,DEVOLUCION)%>%
    mutate(Saldo = PRESTAMO + FRUTA + DEVOLUCION)%>%
    filter(Tipo_material != "AUX")
    
    
    

)
   


```




### Grafico
```{r}
renderPlotly( 
if(input$INTERVALO == "Semana"){



(ggplot(flujos_productor()%>%
           ddply(.(Semana, Tipo_material, Presentacion), summarize, 
                      Total = sum(Total)), 
                aes( x = Semana, y = Total, colour = Presentacion, group = Presentacion)) + geom_line())%>%
                ggplotly()
            
}else{
  
   
  (ggplot(flujos_productor()%>%
           ddply(.(Fecha, Tipo_material, Presentacion), summarize, 
                      Total = sum(Total)), 
                aes( x = Fecha, y = Total, colour = Presentacion, group = Presentacion)) + geom_line())%>%
                ggplotly()

}

)
```

###TABLA

```{r}
renderDataTable(
if(input$INTERVALO == "Semana"){



  datatable(flujos_productor()%>%
              ddply(.(Semana, Clave_productor, Concepto, Tipo_material, Presentacion), summarize, Total = sum(Total))
              , extensions = 'Buttons', options = list(
    autoWidth = TRUE, dom = 'Bfrtip',
    buttons = c('copy', 'csv', 'pdf', "print")))
}else{
  
    datatable(flujos_productor()%>%
                select(-Semana)%>%
              arrange(Fecha), extensions = 'Buttons', options = list(
    autoWidth = TRUE, dom = 'Bfrtip',
    buttons = c('copy', 'csv', 'pdf', "print")))
  
} 
)
```





































ACOPIOS {data-navmenu="MATERIALES"}
=======================================================================================


Nombre
--------------------------------------------------------------------------

###ACOPIO
```{r}

renderValueBox(valueBox(input$Acopio))



```


VISUALIZACION {.tabset}
--------------------------------------------------------------------------------------

###Flujos 
```{r}
renderPlotly(
  (ggplot(inventario()%>%
                  arrange(Fecha)%>%
    group_by(Clave_acopio, Clave_material)%>%
    mutate(Acumulado = cumsum(Flujo))%>%
    ungroup()%>%
      get.material(Campos = c("Material")),
  aes(x = Fecha, y = Acumulado, 
      colour = Material)) + geom_line())%>%
    ggplotly()
)
```



###Datos
```{r}
renderDataTable(
  datatable(inventario()%>%
              ddply(.(Clave_material), summarize, Inventario = sum(Flujo))%>%
              get.material(Campos = c("Material"))%>%
              select(Clave_material, Material, Inventario), rownames = FALSE )
)        
```







